### ISSUE TITLE
The Matlab proxy fails

### ISSUE THREAD

**Issue by roohy466** [mathworks/matlab-proxy#4]
==================================================================================================================================================
                                                            MATLAB can be accessed at:                                                            
                                                           http://0.0.0.0:57731/matlab                                                            
==================================================================================================================================================
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/matlab_proxy/app_state.py", line 576, in start_matlab
    xvfb_cmd, dpipe = create_xvfb_cmd()
  File "/usr/local/lib/python3.9/site-packages/matlab_proxy/settings.py", line 214, in create_xvfb_cmd
    dpipe = os.pipe2(os.O_NONBLOCK)
AttributeError: module 'os' has no attribute 'pipe2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/matlab-proxy-app", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/matlab_proxy/app.py", line 621, in main
    app = configure_and_start(app)
  File "/usr/local/lib/python3.9/site-packages/matlab_proxy/app.py", line 563, in configure_and_start
    loop.run_until_complete(start_background_tasks(app))
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/matlab_proxy/app.py", line 492, in start_background_tasks
    await matlab_starter(app)
  File "/usr/local/lib/python3.9/site-packages/matlab_proxy/app.py", line 478, in matlab_starter
    await state.start_matlab()
  File "/usr/local/lib/python3.9/site-packages/matlab_proxy/app_state.py", line 594, in start_matlab
    log_error(logger, err)
  File "/usr/local/lib/python3.9/site-packages/matlab_proxy/util/mwi/exceptions.py", line 153, in log_error
    logs_str = ("\n" + "\n".join(err.logs)) if err.logs is not None else ""
AttributeError: 'AttributeError' object has no attribute 'logs'

**Comment by diningPhilosopher64** [comment]
Hi @roohy466 ,

Thank you for trying out the matlab-proxy package. 

Can you share the type of Operating System and its version you are running the integration from ?

Thanks,
Sourabh.

**Comment by diningPhilosopher64** [comment]
Hi @roohy466 ,

If you are running the integration( ie. the matlab-proxy-app) from a MacOS system, this error is expected.

The `matlab-proxy` package is designed for Linux environments, if you have access to a linux system or a docker environment, you can use the [MATLAB container](https://hub.docker.com/r/mathworks/matlab) for launching matlab-proxy.

If you want to install matlab-proxy in  a custom docker image, you can check the [examples](https://github.com/mathworks/matlab-proxy/tree/main/examples) folder in the repository.

The development teams have been notified about your interest in using `matlab-proxy` with MacOS.

Please feel free to re-open this issue if you need more help.

Thanks,
Sourabh.
